declare module 'ln-service'
declare module 'opennode'
declare module 'macaroons.js'
declare module 'blgr'
declare module 'binet'
declare module '@lntools/crypto'
declare module 'secp256k1'
declare module 'request-promise-native'
