declare module 'ln-service'
declare module 'opennode'
declare module 'macaroons.js'
declare module 'blgr'
declare module 'binet'
declare module 'bcrypto'
declare module 'request-promise-native'
declare module 'zbase32'
